name: hwacc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - pillow
  - tqdm
  - joblib
  - networkx
  - pytorch>=2.0
  - torchvision
  - pytest
  - pip
  - pip:
      - onnx
      - onnxruntime
      - rectpack
      - sty
